baseURL = "http://www.neucube.io/"
languageCode = "en-us"
title = "NeuCube IO"
theme="neucube-landing"

googleAnalytics = "UA-130186238-1" # Optional
disqusShortname = "" # Optional
pygmentsCodeFences = true
enableRobotsTXT = true

[outputFormats]
  [outputFormats.searchindex]
    mediaType= "application/json"
    baseName= "searchindex"
    isPlainText= true


[outputs]
  home= ["HTML","RSS", "AMP", "searchindex"]

[params]
    amp = true
    year = 2019
    # logoSVG = "img/logo.svg" # # Use logoSVG or logo. Optional
    # logo = "" # Use logoSVG or logo. Optional
    logoPhoto = "" # Use logoSVG or logo or logoPhoto. Optional
    acknowledge = false
    affiliation = "Knowledge Engineering and Discovery Research Institute, AUT University"
    address = "2 Wakefield Street,<br>Auckland CBD, Auckland - 1010<br>New Zealand."
    [params.scss]
        primary = "#000"
        secondary = "gray"
        backgroundColor = "#fff"
        backgroundColorLight = "#272a2c"
        backgroundColorDark = "#000"
        textColor = "#000"
        textColorLight = "gray"
        subTextColor = "gray"
        # globalFontFamilyURL = "https://fonts.googleapis.com/css?family=Space+Mono:400,700" # Not used yet. See https://github.com/gohugoio/hugo/issues
        globalFontFamily = "'Oxygen', sans-serif"
        labelBackgroundColor = "#997953"
        labelTextColor = "#000"